
== Getting Containers

This chapter is about how and where to get ready built container images.


=== {sle} Base Images

{suse} offers a large number of official container base images, which users can use to build containers with. Each base image {slea} contains the {slea} OS of a particular {slea} release minus the kernel. The OS contained in the base image is an empty environment without any further functionality. You, as a user, put your own workload into it, to make it functional.

Base images are available through the {suse} Registry under `registry.suse.com`. For details about {suse} Registry see <<_suse_registry>>. The images you can find in the {suse} Registry are all Generally Available (Production) and link:https://www.suse.com/products/long-term-service-pack-support/[LTSS] releases of SLES 12 and SLES 15. The available images are all compressed to a minimal size of *40MB*. {sle} base images in {suse} Registry are also fully supported, which means they get regularly updated with security fixes and the {suse} support plans apply. For more information about the support plans see <<_supportability>>.

=== {suse} Container Properties

{suse} container images have a number of properties, which can be useful to the user for identifying the right one.
The individual properties listed below can be accessed after you have pulled a container image from the repository and run `docker inspect` on it.

==== Repository names

Repository names start with the name of the product, e.g. `suse/sle/(...)`, `opensuse/tumbleweed/(...)`, `caasp/(...)` and etc.
All {slea} 15 containers for all service packs are in the namespace `suse/sle15`.
This strategy will also be applied to future versions of {slea}, e.g. `suse/sle16` and so on.
For {slea} 12 however, there is a separate repository name for each service pack, e.g. `suse/sle12sp3`, `suse/sle12sp4`, `suse/sle12sp5`.

////
===== Restrictions on projects for publishing images
There are also certain restrictions on projects for publishing images. For every repository in the {suse} Registry (e.g. `suse/sle15` and `opensuse/tumbleweed`), there is exactly one project or repository combination on the Internal Build Service which provides the images to feed those.
This means, you might run into this issue easily if it's required that foo/bar:12.3 is built against SLE 12 SP3, but foo/bar:15.0 against SLE 15, this is not possible with the current setup of CR projects.

SLE deals with this issue by publish disabling SUSE:Containers:SLE-SERVER:15-SP? and using _aggregates to publish the images from the SUSE:Containers:SLE-SERVER:15 project.
openSUSE Leap does it the same way, see also https://en.opensuse.org/Building_derived_containers#Release_mechanism.
////

==== Labels

Labels are another way to identify images. All {slea} container image labels begin with `com.suse.<product>.<containername>` after which follows a further specification. {opensuse} container images are identified by a label that begins with `org.opencontainers`.


[IMPORTANT]
.The `com.suse.sle.base` label is protected.
====
With every new layer added to a base image, labels defined in the base container get overwritten by labels in the derived image. And because the base images are only the bare OS and any functionality added by the user leads to the creation of a new layer, the labels get overwritten very easily. In order to protect information about the origin of the image, the label `com.suse.sle.base` has been added to {slea} container images. This signifies that {suse} is the vendor of this image and this label *must not be overwritten in derived images*. For example the label `com.suse.sle.base.title` contains the image name "SUSE Linux Enterprise 15 Base Container", which is information that cannot be overwritten with any other layer of the image.

The opposite is true for {opensuse} base images, where labels do get overwritten. For example `org.opencontainers.image.title` can get overwritten and will always contain the title of the latest added layer.
====

A list of all currently defined labels follows:

.Currently Defined Labels
|===
|Must be provided by derived images | Labels | OCI Annotation | Description | Example

|✓	|org.opencontainers.image.*title* com.suse.sle.base.*title*	| org.opencontainers.image.title	| Title of the image	| SUSE Linux Enterprise 15 Base Container
|✓	|org.opencontainers.image.*description* com.suse.sle.base.*description*	| org.opencontainers.image.description	| Short description of the image	| Image containing a minimal environment for containers based on SUSE Linux Enterprise 15.
|✓	|org.opencontainers.image.*version* com.suse.sle.base.*version*	| org.opencontainers.image.version | Version of the image | <codestream>.<sp>.<cicnt>.<bldcnt>	15.0.4.2
|✓	|org.opencontainers.image.*created* com.suse.sle.base.*created*	| org.opencontainers.image.created | Date/time of image build	| 2018-07-27T14:12:30Z
|X	|org.opencontainers.image.*vendor* com.suse.sle.base.*vendor*	| org.opencontainers.image.vendor	| Vendor of the image	| SUSE LLC
|X	|org.opencontainers.image.*url* com.suse.sle.base.*url*	| org.opencontainers.image.url	| URL with more information	| https://www.suse.com/products/server/
|✓	|org.openbuildservice.*disturl* com.suse.sle.base.*disturl*	| org.openbuildservice.disturl	| Dist URL as provided by OBS	| obs://build.suse.de/SUSE:SLE-15:Update:CR/images/2951b67133dd6384cacb28203174e030-sles15-image
|✓	|org.opensuse.*reference* com.suse.sle.base.*reference*	| org.opensuse.reference	| Reference pointing to this specific image. The image you get with docker pull <ref.name> must not change.	| registry.suse.com/suse/sle15:4.2
|===

==== Tags

Tags can be freely defined. During the release of a new build, the new builds are released into the target project (See Base Container Image Building) and the old images are kept. If a tag is provided by multiple images, the newest image is used.

Which tags a container image provides is entirely up to the maintainer of the image, as this varies depending on the use case. Consider the restriction explained in "Restrictions on projects for publishing images" above.

[[suse-registry]]
=== {suse} Registry

The official {suse} Registry can be found under `registry.suse.com`. It is the only place from which to pull official tested and updated SLE and SLES base container images. All images in the {suse} Registry undergo a fixed maintenance process, they are regularly updated and security fixes applied.
{suse} Registry free for everyone to use, but much more useful with an active customer subscription on the container host.
That is because the subscription is used by the container and it is needed for the container images to get updates.
The {suse} Registry as of now does not have a UI or a list of images, but all available images are listed in the examples in the
link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#Building-Pre-build-Images[Docker Quickstart Guide],
which is also where you will find a description of how the image names are derived.


[[comparing-containers]]
=== Comparing Containers

The link:https://github.com/GoogleContainerTools/container-diff#container-diff[container-diff]
a useful tool for analyzing and comparing container images.
*`container-diff`* can examine images along several different criteria, including:

* Docker Image History
* Image file system
* Apt packages
* RPM packages
* pip packages
* npm packages

These analyses can be performed on a single image, or a `diff` can be performed on two images to compare.
`container-diff` supports Docker images located in both a local Docker daemon and a remote registry.
Tarballs with the correct extension (.tar, .tar.gz, .tgz) can also be provided to the tool directly.

The `container-diff` package is part of the {sls} 15 SP2 *Containers Module* or it can be installed separately.
For instructions on how to install it,
see the link:https://github.com/GoogleContainerTools/container-diff#installation[container-diff documentation].


=== On-premise Registry

////
http://port.us.org/
https://documentation.suse.com/sles/12-SP4/html/SLES-all/cha-registry-installation.html#sec-docker-portus
or
https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#sec-docker-portus


Portus is an open source authorization service and user interface for the next generation Docker Registry.

It is an on-premise application that allows users to administrate and secure their Docker registries.

As explained here one of the main jobs of Portus is being an authorization service for your Docker registry. The other main goal of Portus is to provide a useful and powerful UI on top of your registry. You can learn about all this here.
////

=== 3rd Party Containers
