
== Getting Containers

This chapter is about how and where to get ready built container images.


=== {sle} Base Images

{suse} offers a large number of official base container images, which users can use to build containers with. Each base image {slea} contains the {slea} OS of a particular {slea} release minus the kernel. Base images are available through the {suse} Registry under `registry.suse.com`. For details about {suse} Registry see <<_suse_registry>>. The images you can find in the {suse} Registry are all Generally Available (Production) and link:https://www.suse.com/products/long-term-service-pack-support/[Long Term Service Pack Support] releases of SLES 12 and SLES 15. The available images are all compressed to a minimal size of 40MB. {sle} base images in {suse} Registry are also fully supported, which means they get regularly updated with security fixes and the {suse} support plans apply. For more information about the support plans see <<_supportability>>.

=== {suse} Container Properties

[[_suse_registry]]
=== {suse} Registry

The official {suse} Registry can be found under `registry.suse.com`. It is the only place from which to pull official tested and updated SLE and SLES base container images. All images in the {suse} Registry undergo a fixed maintenance process, they are regularly updated and security fixes applied.
{suse} Registry free for everyone to use, but much more useful with an active customer subscription on the container host.
That is because the subscription is used by the container and it is needed for the container images to get updates.
The {suse} Registry as of now does not have a UI or a list of images, but all available images are listed in the examples in the
link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#Building-Pre-build-Images[Docker Quickstart Guide],
which is also where you will find a description of how the image names are derived.


=== Comparing Containers

The link:https://github.com/GoogleContainerTools/container-diff#container-diff[container-diff]
a useful tool for analyzing and comparing container images.
*`container-diff`* can examine images along several different criteria, including:

* Docker Image History
* Image file system
* Apt packages
* RPM packages
* pip packages
* npm packages

These analyses can be performed on a single image, or a `diff` can be performed on two images to compare.
`container-diff` supports Docker images located in both a local Docker daemon and a remote registry.
Tarballs with the correct extension (.tar, .tar.gz, .tgz) can also be provided to the tool directly.

The `container-diff` package is part of the {sls} 15 SP2 *Containers Module* or it can be installed separately.
For instructions on how to install it,
see the link:https://github.com/GoogleContainerTools/container-diff#installation[container-diff documentation].


=== On-premise Registry

=== 3rd Party Containers
